# Generated by Django 2.1.1 on 2019-03-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
