# Generated by Django 2.1.1 on 2018-09-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180927_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='first_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='question',
            new_name='category',
        ),
    ]
