# Generated by Django 2.1.1 on 2018-10-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180927_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_shortname_th',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
