# Generated by Django 2.1.1 on 2018-10-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_shop_shop_shortname_th'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_details_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_details_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_shortname_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
