# Generated by Django 2.1.1 on 2018-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20181012_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
