# Generated by Django 2.1.1 on 2018-10-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_shop_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='cat_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='icon',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
