# Generated by Django 2.1.1 on 2018-10-12 08:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20181012_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='floor',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128),
        ),
    ]
