# Generated by Django 2.1.1 on 2018-10-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20181012_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='tel',
        ),
    ]
