# Generated by Django 2.1.1 on 2018-10-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20181012_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='active',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='icon',
        ),
    ]
