# Generated by Django 2.1.1 on 2018-10-12 08:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20181012_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='branch_code',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='cat_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='create_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='floor',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='icon',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='pivot_icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_by',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='shop',
            name='x_pivot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='y_pivot',
            field=models.FloatField(default=0),
        ),
    ]
