# Generated by Django 2.1.1 on 2018-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20181012_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='cat_id',
        ),
        migrations.AlterField(
            model_name='shop',
            name='branch_code',
            field=models.CharField(default=None, max_length=4),
        ),
    ]
