# Generated by Django 2.1.1 on 2018-10-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20181017_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='create_date',
            field=models.DateTimeField(default=None, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_date',
            field=models.DateTimeField(default=None, verbose_name='update date'),
        ),
    ]
