# Generated by Django 2.1.1 on 2018-10-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20181017_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pub_date',
        ),
    ]
