# Generated by Django 2.1.1 on 2018-10-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_category_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Platform Budget Cost Data', 'verbose_name_plural': 'Platform Budget Cost Data'},
        ),
    ]
