# Generated by Django 2.1.1 on 2018-10-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20181017_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
