# Generated by Django 2.1.1 on 2018-10-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20181018_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='shop_pic',
            field=models.ImageField(upload_to='uploads/', verbose_name='image'),
        ),
    ]
