# Generated by Django 2.1.1 on 2018-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20181018_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='shop_pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
