# Generated by Django 2.1.1 on 2018-10-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20181031_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='floor',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default=None, max_length=10),
        ),
    ]
