# Generated by Django 2.1.1 on 2018-10-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20181031_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='floor',
            field=models.CharField(choices=[('EMP', (('Floo1', 'Floo1'), ('M', 'M'))), ('EMQ', (('G', 'G'), ('Floo1', 'Floo1'), ('M', 'M')))], default=None, max_length=10),
        ),
    ]
