# Generated by Django 2.1.1 on 2018-10-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20181031_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=None, max_length=10),
        ),
    ]
