# Generated by Django 2.1.1 on 2018-10-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_shop_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='active',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='branch_code',
            new_name='Branch_Code',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_type',
            new_name='Cat_ID',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='create_by',
            new_name='Create_by',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='create_date',
            new_name='Create_date',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='floor',
            new_name='Floor',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_details_en',
            new_name='Shop_Detail_EN',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_details_th',
            new_name='Shop_Detail_TH',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='Shop_Name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_shortname_en',
            new_name='Shop_ShortName_EN',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_shortname_th',
            new_name='Shop_ShortName_TH',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='tel',
            new_name='Tel',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='updated_by',
            new_name='Updated_by',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='updated_date',
            new_name='Updated_date',
        ),
        migrations.AddField(
            model_name='shop',
            name='Shop_ID',
            field=models.IntegerField(default=1),
        ),
    ]
