# Generated by Django 2.1.1 on 2019-01-10 05:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(default=None, help_text='This field is required.', max_length=20, verbose_name='ชื่อแคท')),
                ('Parent_ID', models.IntegerField(null=True)),
                ('Cat_Level', models.IntegerField(null=True)),
                ('Active', models.BooleanField(default=True, help_text='This field is required.')),
                ('Create_date', models.DateTimeField(default=datetime.datetime(2019, 1, 10, 12, 29, 36, 222449), help_text='This field is required.', verbose_name='Create Date')),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2019, 1, 10, 12, 29, 36, 222449), help_text='This field is required.', verbose_name='Update Date')),
                ('Test', models.CharField(default=None, max_length=20)),
                ('Floor', models.CharField(choices=[('EMP', (('Floo1', 'Floo1'), ('M', 'M'))), ('EMQ', (('G', 'G'), ('Floo1', 'Floo1'), ('M', 'M')))], default=None, help_text='This field is required.', max_length=10)),
                ('create_by', models.ForeignKey(help_text='This field is required.', on_delete=django.db.models.deletion.CASCADE, related_name='UserXXX', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='This field is required.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_pic', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_ID', models.IntegerField(null=True)),
                ('Shop_Name', models.CharField(max_length=200, null=True)),
                ('Shop_ShortName_TH', models.CharField(max_length=200, null=True)),
                ('Shop_ShortName_EN', models.CharField(max_length=200, null=True)),
                ('Shop_Detail_TH', models.TextField(max_length=200, null=True)),
                ('Shop_Detail_EN', models.TextField(max_length=200, null=True)),
                ('Shop_type', models.CharField(choices=[('Brand', 'Brand'), ('Shop', 'Shop')], help_text='This field is required.', max_length=20)),
                ('Active', models.BooleanField(default=True, help_text='This field is required.')),
                ('icon', models.ImageField(default=None, help_text='This field is required.', upload_to='')),
                ('cover', models.ImageField(default=None, help_text='This field is required.', upload_to='')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Floor', models.CharField(choices=[('EMP', (('Floo1', 'Floo1'), ('M', 'M'))), ('EMQ', (('G', 'G'), ('Floo1', 'Floo1'), ('M', 'M')))], default=None, help_text='This field is required.', max_length=10)),
                ('Tel', models.CharField(max_length=20, null=True)),
                ('Branch_Code', models.CharField(choices=[('EMP', 'EMP'), ('EMQ', 'EMQ')], default=None, help_text='This field is required.', max_length=4)),
                ('pivot_icon', models.CharField(max_length=20, null=True)),
                ('x_pivot', models.FloatField(default=0, null=True)),
                ('y_pivot', models.FloatField(default=0, null=True)),
                ('Create_date', models.DateTimeField(default=None, help_text='This field is required.', verbose_name='create date')),
                ('Updated_date', models.DateTimeField(default=None, help_text='This field is required.', verbose_name='update date')),
                ('Create_by', models.ForeignKey(help_text='This field is required.', on_delete=django.db.models.deletion.CASCADE, related_name='UserXXXX', to=settings.AUTH_USER_MODEL)),
                ('Updated_by', models.ForeignKey(help_text='This field is required.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='emcms.Categories')),
            ],
        ),
    ]
