# Generated by Django 2.1.1 on 2019-02-04 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emcms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='Floor',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='Test',
        ),
        migrations.AlterField(
            model_name='categories',
            name='Cat_Name',
            field=models.CharField(default=None, help_text='This field is required.', max_length=20),
        ),
        migrations.AlterField(
            model_name='categories',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 14, 33, 1, 367304), help_text='This field is required.', verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 14, 33, 1, 367304), help_text='This field is required.', verbose_name='Update Date'),
        ),
    ]
