# Generated by Django 2.1.1 on 2019-02-07 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emcms', '0003_auto_20190204_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 13, 55, 44, 787913), help_text='This field is required.', verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 13, 55, 44, 787913), help_text='This field is required.', verbose_name='Update Date'),
        ),
    ]
