# Generated by Django 2.1.1 on 2019-02-12 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emcms', '0004_auto_20190207_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 12, 13, 15, 24, 56113), help_text='This field is required.', verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 12, 13, 15, 24, 56113), help_text='This field is required.', verbose_name='Update Date'),
        ),
    ]
