# Generated by Django 2.1.1 on 2019-03-22 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emcms', '0005_auto_20190212_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 15, 43, 43, 90666), help_text='This field is required.', verbose_name='Create Date'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 15, 43, 43, 90666), help_text='This field is required.', verbose_name='Update Date'),
        ),
    ]
